# Netlify configuration for DuitTrack
# Production-ready settings for fintech app with Firebase integration

[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# Security Headers for fintech application
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy - Firebase Auth & Google Sign-In compatible
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.gstatic.com https://apis.google.com https://*.firebaseapp.com https://*.googleapis.com https://accounts.google.com https://www.google.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://accounts.google.com;
      font-src 'self' https://fonts.gstatic.com https://accounts.google.com;
      connect-src 'self' https://*.gstatic.com https://*.firebaseapp.com https://*.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://firebase.googleapis.com https://firebaseinstallations.googleapis.com https://accounts.google.com https://*.googleusercontent.com https://oauth2.googleapis.com https://www.googleapis.com https://content.googleapis.com https://iid.googleapis.com https://fcmregistrations.googleapis.com;
      img-src 'self' data: blob: https: https://*.googleusercontent.com https://accounts.google.com;
      frame-src 'self' https://accounts.google.com https://content.googleapis.com https://*.firebaseapp.com;
      child-src 'self' https://accounts.google.com blob:;
      worker-src 'self' blob: https://*.gstatic.com;
      object-src 'none';
      base-uri 'self';
    """

    # Frame Protection
    X-Frame-Options = "DENY"

    # Content Type Sniffing Protection
    X-Content-Type-Options = "nosniff"

    # XSS Protection (legacy browsers)
    X-XSS-Protection = "1; mode=block"

    # Referrer Policy
    Referrer-Policy = "strict-origin-when-cross-origin"

    # HSTS - Force HTTPS
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

    # Permissions Policy (Feature Policy)
    Permissions-Policy = """
      geolocation=(),
      microphone=(),
      camera=(),
      payment=(),
      usb=(),
      magnetometer=(),
      gyroscope=(),
      accelerometer=()
    """

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# PWA manifest and service worker - don't cache
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirect rules
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom error pages
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# Environment variables (use Netlify UI to set actual values)
# FIREBASE_API_KEY
# FIREBASE_AUTH_DOMAIN
# FIREBASE_PROJECT_ID
# FIREBASE_STORAGE_BUCKET
# FIREBASE_MESSAGING_SENDER_ID
# FIREBASE_APP_ID
# FIREBASE_MEASUREMENT_ID
